# Generated by Django 2.1.15 on 2020-06-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('file_path', models.FileField(upload_to='data')),
            ],
        ),
    ]
